### ISSUE TITLE
A form's header text is not aligned vertically.

### ISSUE THREAD

**Issue by vadimv** [altsoft/PlatypusJS#10]
![form-header](https://cloud.githubusercontent.com/assets/938875/7690235/9558c088-fdb2-11e4-8847-97c657de2233.png)
Result: the form's header text is not centered vertically.
Expected: the text should be aligned to center vertically in the header.

**Comment by marat-gainullin** [comment]
With different fonts in window-caption[-active] class in theme.css there will be different round errors on top or om bottom.
