### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by hcspidergrasp** [altsoft/PlatypusJS#11]
'Failed to load resource' in GWT if server down on cordova based mobile client.
Unable to catch this exception with window.onerror.

**Comment by marat-gainullin** [comment]
P.onError was implemented. It has an only argument - errorMessage. It is called when some network error occures while performing some low-level request to the server. Other requests are made by application and there is an error callback. Low-level requests have no application failure callback and so P.onError is called.
