### ISSUE TITLE
Critical: debugger is not working at all!!!

### ISSUE THREAD

**Issue by AlexeyKashintsev** [altsoft/PlatypusJS#19]

**Comment by marat-gainullin** [comment]
Unfortunatly, It is Nashorn issue. Hope Java 9 will fix it.

**Comment by marat-gainullin** [comment]
Fortunatly oracle has fixed some issues related with debugging of nashorn script. Than i have replaced NetBeans JSJavaBreakpointsManager and everything became fine. The interesting issue apears when JIT compilation of hot methods in Nashorn generated classes takes place. Breakpoints are accepted by JDI server, but no events occur when corresponding code is executed. So some breakpoints don't work. The workaround is to add -Xint command line switch to debuggee command line. Without JIT compilation all breakpoints work even if they were reached in several parallel threads of a debugged application.
