### ISSUE TITLE
Web form is not updated after changing its design.

### ISSUE THREAD

**Issue by vadimv** [altsoft/PlatypusJS#2]
Steps to reproduce:
1. Create a form and add a button on it.
2. Run the application as a web application. Check the position of the button in the browser.
3. Change the positioning of the button.
4. Refresh (F5) the page.
Result: the form's stays the same.
Expected: the form's design should be updated.

**Comment by vadimv** [comment]
The form updated after ~1 min. Too slow..

**Comment by jskonst** [comment]
Often this caused by browser's cache. Try to disable it. In chrome-based browsers it called - "Disable cache (while DevTools is open)". If problem still remain - please write us.
