### ISSUE TITLE
Network issues cause hanging of Platypus Designer

### ISSUE THREAD

**Issue by hcspidergrasp** [altsoft/PlatypusJS#27]
As far DB diagram work with database directly, opening a DB diagram during miss of the Internet cause permanent designer process hanging even if network back to normal again.
It would be cool to prevent this hanging and display network error message.

PS: It's normal when DB server not available. Hanging happens only if there is not Internet at all. Right now the only cure is process kill.

**Comment by marat-gainullin** [comment]
Occures only when there are dns0like internet problems.

**Comment by marat-gainullin** [comment]
Unconfirmed. Not long period of time ago some deadlock were fixed in Nightly build. Hope this will help. Check it please again and reopen this issue if nothing change.
