### ISSUE TITLE
Remove netbeans generated stub header from every *.js file in the project.

### ISSUE THREAD

**Issue by vadimv** [altsoft/PlatypusJS#33]
Remove  
```
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
```
noise from every java class file.

**Comment by marat-gainullin** [comment]
May be *.js files?

**Comment by marat-gainullin** [comment]
Platypus.js mmodules have no such noise.
Standard NetBeans *.js files template should be edited by user or by authors of NetBEans *.js files template.
