### ISSUE TITLE
A property and an event hanlders did not removed when a widget removed in the designer.

### ISSUE THREAD

**Issue by vadimv** [altsoft/PlatypusJS#4]
Steps to reproduce:
1. Add a button on a form.
2. Double click on the button to create a handler:
```javascript
form.button.onActionPerformed = function(event) {
    };
```
3. Remove the button from the designer.
Result: The added handler stays unchanged. The code is in a broken state.
Expected result: The property and handler should be removed automatically.

**Comment by marat-gainullin** [comment]
Noe they are not added as well. Designer is no longer responsible of js code generation at all.
