### ISSUE TITLE
Drop down: selected values are invisible in designer on mac

### ISSUE THREAD

**Issue by AlexeyKashintsev** [altsoft/PlatypusJS#47]
They are visible only if field is selected in other case it looks like an empty field.
<img width="270" alt="2015-09-14 18 20 25" src="https://cloud.githubusercontent.com/assets/5558987/9855265/7d822432-5b0d-11e5-8660-b669f4bc40dc.png">

**Comment by marat-gainullin** [comment]
Should be reported to NetBeans issue tracker.
