### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by AlexeyKashintsev** [altsoft/PlatypusJS#53]
Platform files are not copying to a web and WEB-INF folders on deployment at least on mac os.
And mtd_* tables are not created

**Comment by AlexeyKashintsev** [comment]
It happens even update platform's API is checked in project settings

**Comment by marat-gainullin** [comment]
It might be because of git/already runner designer issue.
Now designer re-reads private.properties file before launch and so the issue is likely to be eliminated.
