### ISSUE TITLE
modelGrid.selected пустой после обновления данных

### ISSUE THREAD

**Issue by minya92** [altsoft/PlatypusJS#55]
При обновлении  данных запроса у modelGrid поле selected не содержит в себе никаких данных, хотя cursor установлен на первый элемент grid'a.

**Comment by marat-gainullin** [comment]
Это правильно. Курсор и выделение никак не связаны. Если Вам нужно чтобы после обновления данных элемент данных, на который указывает курсор был выделен, воспользуйтесь методом ModelGrid.select().
