### ISSUE TITLE
.query like params

### ISSUE THREAD

**Issue by AlexeyKashintsev** [altsoft/PlatypusJS#61]
Add .query like params into another data requesting commands:
requery, execute, executeUpdate

example:
command({param1: val, param2: val}, success, failure)

**Comment by marat-gainullin** [comment]
New method `update()` implemented.
For `requery()`, `execute() and `executeUpdate()` it is not actual.
It should be fine to use `query()` and `update()` methods in a new manner.
Available in nightly build.
