### ISSUE TITLE
Upload image in HTML-Area

### ISSUE THREAD

**Issue by jskonst** [altsoft/PlatypusJS#62]
After image have been uploaded in HTML-Area, it has view like "[&quot;http://platypus-platform.org:8085/platypusuidemo/pub/146286892624219-editor-fonts.gif &quot;]" , but elements [&quot; and &quot;] - are unnecessary. Removing them manually - fixes problem

**Comment by marat-gainullin** [comment]
It was because of buggy code in PlatypusHtmlEditor, wich won't parse JSON returned by server after upload. Now it is fixed and fix is available in nightly build.
