### ISSUE TITLE
No visible TAB Events

### ISSUE THREAD

**Issue by cbsistem** [altsoft/PlatypusJS#63]
Install Platypus  version 5.4.
No visible tab Events

Help me please

tanks

Cristiano Barbosa
Brazil

**Comment by marat-gainullin** [comment]
In designer there is no tab "events" at all. Since Platypus.js UI is widgets based, events of any widget is standard JavaScript functional property and should be assigned at runtime. There are no "events attributes of tags" and events handlers manupulation is up to you.

**Comment by cbsistem** [comment]
Check image extrated in video youtube.   Tab Events

![tabsheet events](https://cloud.githubusercontent.com/assets/189597/15185237/48ae2fe2-1766-11e6-9c9f-f83a9e3c7cb6.png)
nts in property

**Comment by marat-gainullin** [comment]
Yes, you are right. In Platypus.js 5.4 we have removed this feature because of strict JavaScript principles.
