### ISSUE TITLE
HowTo Build PlatypusJS

### ISSUE THREAD

**Issue by cbsistem** [altsoft/PlatypusJS#67]
Exist HowTo or screencast to Build PlatypusJS  ?

**Comment by marat-gainullin** [comment]
Not yet.

There is hudson CI configuration (hudsonci/config.xml) that invokes ant to build all Platypus.js parts, including installation packs. You may look there.

Also, there are NetBeans projects "application/src/group", "designer" and Eclipse project "web-client/src/platypus". If you build them and perform two extra steps (copy with overwrite folder " web-client/src/pwc-external" to folder where platypus browser client is linked by the gwt and copy the result to folder "application/bin/pwc"), you will get a fresh version of Platypus.js without installation packs.

**Comment by cbsistem** [comment]
HowTo Build all Java Class to Generate fresh version of Platypus.js
-----------------------------------------------------------------------------------------------
Download source code https://github.com/altsoft/PlatypusJS

Estructure Foltder
-------------------------------
application  => source files javascript Platypus Platform
|   |__lib			> lib jar files used by Runtime Platypus Platform
|   |__src			> files java responsable Bridge JavaScript Platypus Platform (build in NetBeans)
|   |    |___group	> All NetBeans Group 
|   |    |___lib		> Java class  (use no identificate) 
|
|___designer		> IDE Design vinculate in NetBeans 
|___hudsonci
|___installer		>  Java Class Create instalator 
|___web_client		> Eclipse Project 
    |___src
    |    |___platypus
    |    |   |___src	> Java class responsable to create javascript object = gwt
    |___pwc_external

1. Invokes Ant to build all Platypus.js including installation packs 
   1.1 Hudson CI configuration (hudsonci/config.xml)   (opcional)
2. NetBeans projects 
    "application/src/group", "designer" 
3. Eclipse project 
    "web-client/src/platypus".
4. After you build them 
   4.1 Copy with overwrite folder " web-client/src/pwc-external" to folder where platypus browser client is linked by the gwt
  4.2 Copy the result to folder "application/bin/pwc"

Now you will get a fresh version of Platypus.js without installation packs.




[estrutura.txt](https://github.com/altsoft/PlatypusJS/files/260211/estrutura.txt)

**Comment by marat-gainullin** [comment]
build-instructions.md created in root folder.

**Comment by cbsistem** [comment]
Please check list build-instructions.md

3 . Type `ant -f ./designer/build.xml clean build -Dnbplatform.default.harness.dir=/home/your-home-dir/your-netbeans-dir/harness/ -Dnbplatform.default.netbeans.dest.dir=/home/your-home-dir/your-netbeans-dir/` on the command line. This will build Platypus IDE and will put it to `./designer/build` folder.

Is equal START destination folder ?
```
/home/your-home-dir/your-netbeans-dir/harness/
/home/your-home-dir/your-netbeans-dir/
```

**Comment by jskonst** [comment]
/home/your-home-dir/your-netbeans-dir/ may be the same, so in you case it may be

ant -f ./designer/run.xml run -Dnbplatform.default.harness.dir=D:\netbeans-8.1\harness -Dnbplatform.default.netbeans.dest.dir=D:\netbeans-8.1

**Comment by cbsistem** [comment]
Yes .. resolved
ant -f ./designer/run.xml run -Dnbplatform.default.harness.dir=%netbeans%/harness/ -Dnbplatform.default.netbeans.dest.dir=%netbeans%/
