### ISSUE TITLE
JavaScript DEVMODE - DEBUG 

### ISSUE THREAD

**Issue by cbsistem** [altsoft/PlatypusJS#68]
It is possible to disable script compression ?

**Comment by jskonst** [comment]
Good day, we are preparing instructions on launching gwt in super-dev-mode and debugging sources. In nearest release of nightly build scripts compression will be turned off

**Comment by marat-gainullin** [comment]
Super dev mode will offer full java source maps within browser's debugger.
Script compression will be turned off at all in nightly builds, regardless of using super dev mode.

**Comment by cbsistem** [comment]
GWT Compiler Options   IN https://gist.github.com/Abdennebi/2828230
 -style                  Script output style: OBF[USCATED], PRETTY, or DETAILED (defaults to OBF)
I do not know how to use this option.
I found the .jar GWT in Platypus packages

**Comment by marat-gainullin** [comment]
Look at line 53 of .../web-client/src/platypus/build.xml

**Comment by cbsistem** [comment]
tanks marat-gainullin
line 4 , original:
	<property name="gwt.args" value="" />
changed
	<property name="gwt.args" value="-logLevel DEBUG -style DETAILED" />

line 46 exists
	<arg line="${gwt.args}" />

this should solve

**Comment by marat-gainullin** [comment]
Yeah. May be you don't nedd DETAILED. In most cases, PRETTY is enough.
