### ISSUE TITLE
Ctrl-S does not save a form's design changes

### ISSUE THREAD

**Issue by vadimv** [altsoft/PlatypusJS#7]
Steps to reproduce:
1. Create a new form. Go to Design tab.
2. Add some widget to the form.
3. Try to save the changes pressing Ctrl-S keys.
Result: The changes on the form are not saved.
Expected result: the design changes should be saved on this keyboard shortcut.

**Comment by hcspidergrasp** [comment]
Have you tried to switch input language? I have same thing on ubuntu, shortcuts work only if english input is currently selected. Same thing with NetBeans, looks like RCP's adorable stupidity ^_^
