### ISSUE TITLE
Platypus Client GUI: text area scrolling

### ISSUE THREAD

**Issue by hcspidergrasp** [altsoft/PlatypusJS#70]
Small, but annoying issue :)
Dont know is this a GUI bug or not, but mouse wheel scrolling not working on text area widget on desktop client.

**Comment by marat-gainullin** [comment]
Let me clarify, does it wok with scrollbars?

**Comment by hcspidergrasp** [comment]
It does, but scrollbars isn't so user friendly :)
Thanks for fixing btw.
