### ISSUE TITLE
Exist Event onKeyPressed to modelGrid ?

### ISSUE THREAD

**Issue by cbsistem** [altsoft/PlatypusJS#76]
is possible example to use?

tanks

**Comment by marat-gainullin** [comment]
I think it is not implemented, but it is nothing impossible, due to `Ctrl+F` and `F3` hot keys exisitance. We will review this question on monday.

**Comment by marat-gainullin** [comment]
`        
       form.modelGrid.onKeyPressed = function (evt) {
            Logger.info('key ' + evt.key + ' pressed');
        };

        form.modelGrid.onKeyReleased = function (evt) {
            Logger.info('key ' + evt.key + ' released');
        };
`

Available in nightly build (on branch master).

**Comment by cbsistem** [comment]
very obrigado..vou download updates.
I will set up the project following the manual.
