### ISSUE TITLE
Web application is broken. -- CANCELLED (Need to check for the details)

### ISSUE THREAD

**Issue by vadimv** [altsoft/PlatypusJS#8]
Steps to reproduce:
1. Create a new project.
2. Select the project's client as web browser and app server as J2EE server.
3. Add some form to the project.
4. Run the project.
Result: browser starts opening broken web page. 
Expected result: web app starts without errors.

**Comment by marat-gainullin** [comment]
META-INF and WEB-INF folders added to the root directory is a new way. Theese folders should be in the root folder to conform WAR structure better.

**Comment by marat-gainullin** [comment]
Hope it will be clear for you in the nearest build.
