### ISSUE TITLE
Custom annotations in queries

### ISSUE THREAD

**Issue by AlexeyKashintsev** [altsoft/PlatypusJS#97]
Add support for custom annotation in queries and processing modules for such queries

For example to log every query

**Comment by marat-gainullin** [comment]
There is a n opportunity to log every query already.
Can you please give me other cases, where such feature would be useful?

**Comment by marat-gainullin** [comment]
Won't handle because of useless feature. There is sql queries logging already. Add another Issue report if queries logging will not satisfy your needs.
